# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: eshopqueue
# spec:
#   type: pubsub.rabbitmq
#   version: v1
#   metadata:
#   - name: host
#     secretKeyRef:
#       name: rabbitmqconnectionstring
#       key: host
#   - name: durable
#     value: "true"
# auth:
#   secretStore: kubernetes
# ---
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: eshopqueues
# spec:
#   type: bindings.rabbitmq
#   version: v1
#   metadata:
#   - name: queueName
#     value: eshop
#   - name: host
#     secretKeyRef:
#       name: rabbitmqconnectionstring
#       key: host
# auth:
#   secretStore: kubernetes

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eshopqueue
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
auth:
  secretStore: kubernetes

# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: eshopqueue
# spec:
#   type: pubsub.azure.servicebus
#   version: v1
#   metadata:
#   - name: connectionString
#     value: "Endpoint=sb://{ServiceBusNamespace}.servicebus.windows.net/;SharedAccessKeyName={PolicyName};SharedAccessKey={Key};EntityPath={ServiceBus}"